//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityDetail
    {
        public int ActivityDetailId { get; set; }
        public int ActivityId { get; set; }
        public int SiteLanguageId { get; set; }
        public string Activity { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> ActivityTypeId { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Activity Activity1 { get; set; }
    }
}
