//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Users_Clusters
    {
        public System.Guid UserClusterId { get; set; }
        public System.Guid UserId { get; set; }
        public int ClusterId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
