//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditAll
    {
        public int AuditId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string TableName { get; set; }
        public string AuditEntry { get; set; }
    }
}
