//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClusterObjective
    {
        public ClusterObjective()
        {
            this.ObjectivePriorities = new HashSet<ObjectivePriority>();
        }
    
        public int ClusterObjectiveId { get; set; }
        public int EmergencyClusterId { get; set; }
        public int ObjectiveId { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmergencyCluster EmergencyCluster { get; set; }
        public virtual ICollection<ObjectivePriority> ObjectivePriorities { get; set; }
    }
}
