//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClusterIndicator
    {
        public ClusterIndicator()
        {
            this.ClusterIndicatorDetails = new HashSet<ClusterIndicatorDetail>();
            this.ClusterReportDetails = new HashSet<ClusterReportDetail>();
            this.SahelIndicatorCountryTargets = new HashSet<SahelIndicatorCountryTarget>();
        }
    
        public int ClusterIndicatorId { get; set; }
        public int EmergencyClusterId { get; set; }
        public int EmergencyLocationId { get; set; }
        public bool IsCommon { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> ClusterTarget { get; set; }
        public int YearId { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrigionalTarget { get; set; }
        public Nullable<bool> IsRegional { get; set; }
        public Nullable<int> IndicatorCalculationTypeId { get; set; }
        public Nullable<int> oldid { get; set; }
        public Nullable<int> newrc { get; set; }
    
        public virtual ICollection<ClusterIndicatorDetail> ClusterIndicatorDetails { get; set; }
        public virtual EmergencyCluster EmergencyCluster { get; set; }
        public virtual EmergencyLocation EmergencyLocation { get; set; }
        public virtual ICollection<ClusterReportDetail> ClusterReportDetails { get; set; }
        public virtual ICollection<SahelIndicatorCountryTarget> SahelIndicatorCountryTargets { get; set; }
    }
}
