//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergency
    {
        public int EmergencyUniqueId { get; set; }
        public int EmergencyId { get; set; }
        public byte SiteLanguageId { get; set; }
        public string EmergencyName { get; set; }
        public int EmergencyTypeId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EmergencyDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public bool IsOPSEmergency { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> IsSRP { get; set; }
    
        public virtual DisasterType DisasterType { get; set; }
    }
}
