//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        public Indicator()
        {
            this.IndicatorClusterTargets = new HashSet<IndicatorClusterTarget>();
            this.IndicatorDetails = new HashSet<IndicatorDetail>();
        }
    
        public int IndicatorId { get; set; }
        public int ActivityId { get; set; }
        public bool IsActive { get; set; }
        public int UnitId { get; set; }
        public bool IsGender { get; set; }
        public int YearId { get; set; }
        public bool IsMigrated { get; set; }
        public Nullable<int> OldIndicatorId { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> IndicatorCalculationTypeId { get; set; }
        public Nullable<int> tempnumber { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ICollection<IndicatorClusterTarget> IndicatorClusterTargets { get; set; }
        public virtual ICollection<IndicatorDetail> IndicatorDetails { get; set; }
    }
}
