//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyFigureSubCategory
    {
        public KeyFigureSubCategory()
        {
            this.KeyFigureIndicators = new HashSet<KeyFigureIndicator>();
            this.KeyFigureSubCategoryDetails = new HashSet<KeyFigureSubCategoryDetail>();
        }
    
        public int KeyFigureSubCategoryId { get; set; }
        public int KeyFigureCategoryId { get; set; }
        public bool IsActive { get; set; }
        public bool IsPopulation { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual KeyFigureCategory KeyFigureCategory { get; set; }
        public virtual ICollection<KeyFigureIndicator> KeyFigureIndicators { get; set; }
        public virtual ICollection<KeyFigureSubCategoryDetail> KeyFigureSubCategoryDetails { get; set; }
    }
}
