//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectivePriority
    {
        public ObjectivePriority()
        {
            this.PriorityActivities = new HashSet<PriorityActivity>();
        }
    
        public int ObjectivePriorityId { get; set; }
        public int ClusterObjectiveId { get; set; }
        public int HumanitarianPriorityId { get; set; }
    
        public virtual ClusterObjective ClusterObjective { get; set; }
        public virtual ICollection<PriorityActivity> PriorityActivities { get; set; }
    }
}
