//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPSProjectDetail
    {
        public int OPSProjectDetailsId { get; set; }
        public int ProjectID { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectCode { get; set; }
        public string Organizationname { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> OriginalRequest { get; set; }
        public string Original_A { get; set; }
        public Nullable<int> Original_A_Amount { get; set; }
        public string Original_B { get; set; }
        public Nullable<int> Original_B_Amount { get; set; }
        public string Original_C { get; set; }
        public Nullable<int> Original_C_Amount { get; set; }
        public string Original_D { get; set; }
        public Nullable<int> Original_D_Amount { get; set; }
        public string Original_E { get; set; }
        public Nullable<int> Original_E_Amount { get; set; }
        public Nullable<int> CurrentRequest { get; set; }
        public string Current_A { get; set; }
        public Nullable<int> Current_A_Amount { get; set; }
        public string Current_B { get; set; }
        public Nullable<int> Current_B_Amount { get; set; }
        public string Current_C { get; set; }
        public Nullable<int> Current_C_Amount { get; set; }
        public string Current_D { get; set; }
        public Nullable<int> Current_D_Amount { get; set; }
        public string Current_E { get; set; }
        public Nullable<int> Current_E_Amount { get; set; }
        public Nullable<int> RunningRequest { get; set; }
        public string Running_A { get; set; }
        public Nullable<int> Running_A_Amount { get; set; }
        public string Running_B { get; set; }
        public Nullable<int> Running_B_Amount { get; set; }
        public string Running_C { get; set; }
        public Nullable<int> Running_C_Amount { get; set; }
        public string Running_D { get; set; }
        public Nullable<int> Running_D_Amount { get; set; }
        public string Running_E { get; set; }
        public Nullable<int> Running_E_Amount { get; set; }
        public string Cluster { get; set; }
        public string Status_LongDs { get; set; }
        public string Province_Name { get; set; }
        public string ObjectiveText { get; set; }
        public Nullable<int> BeneficiaryTotalNumber { get; set; }
        public Nullable<int> BeneficiariesChildren { get; set; }
        public Nullable<int> BeneficiariesWomen { get; set; }
        public Nullable<int> BeneficiariesOthers { get; set; }
        public string BeneficiariesDescription { get; set; }
        public string BeneficiariesTotalDescription { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public string ProjectImplementingpartner { get; set; }
        public string Needs { get; set; }
        public string Activities { get; set; }
        public string Outcomes { get; set; }
        public string Priority { get; set; }
        public string ProjectContactName { get; set; }
        public string ProjectContactEmail { get; set; }
        public string ProjectContactPhone { get; set; }
        public string AgencyProjectCode { get; set; }
        public string RelatedURL { get; set; }
        public string WorkFlowComments { get; set; }
        public Nullable<System.DateTime> ProjectCreatedDate { get; set; }
        public string ProjectType { get; set; }
        public string GenderMarkerCode { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public string SubSetOfAppeal { get; set; }
        public Nullable<bool> ProjectAlreadyInTable { get; set; }
        public Nullable<int> LocationCodeId { get; set; }
        public Nullable<int> ClusterCodeId { get; set; }
        public Nullable<int> NewlyAdded { get; set; }
    }
}
