//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPSReport
    {
        public OPSReport()
        {
            this.OPSReportDetails = new HashSet<OPSReportDetail>();
            this.OPSReportLocations = new HashSet<OPSReportLocation>();
        }
    
        public int OPSReportId { get; set; }
        public int OPSProjectId { get; set; }
        public int EmergencyClusterId { get; set; }
        public int EmergencyLocationId { get; set; }
        public Nullable<byte> SiteLanguageId { get; set; }
        public int YearId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedByIdOPSUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedByIdOPSUser { get; set; }
        public Nullable<bool> ToDelete { get; set; }
    
        public virtual ICollection<OPSReportDetail> OPSReportDetails { get; set; }
        public virtual ICollection<OPSReportLocation> OPSReportLocations { get; set; }
    }
}
