//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ORSEntities : DbContext
    {
        public ORSEntities()
            : base("name=ORSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityData> ActivityDatas { get; set; }
        public virtual DbSet<ActivityDetail> ActivityDetails { get; set; }
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<AllDataStagingEnglish> AllDataStagingEnglishes { get; set; }
        public virtual DbSet<AllDataStagingFrench> AllDataStagingFrenches { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<AspNet_SqlCacheTablesForChangeNotification> AspNet_SqlCacheTablesForChangeNotification { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_Users_Custom> aspnet_Users_Custom { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<AuditAll> AuditAlls { get; set; }
        public virtual DbSet<ClusterIndicatorDetail> ClusterIndicatorDetails { get; set; }
        public virtual DbSet<ClusterIndicator> ClusterIndicators { get; set; }
        public virtual DbSet<ClusterIndicatorTarget> ClusterIndicatorTargets { get; set; }
        public virtual DbSet<ClusterObjective> ClusterObjectives { get; set; }
        public virtual DbSet<ClusterPartner> ClusterPartners { get; set; }
        public virtual DbSet<ClusterReportDetail> ClusterReportDetails { get; set; }
        public virtual DbSet<ClusterReport> ClusterReports { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
        public virtual DbSet<CountryMapDetail> CountryMapDetails { get; set; }
        public virtual DbSet<CountryMap> CountryMaps { get; set; }
        public virtual DbSet<CountryReport> CountryReports { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DisasterType> DisasterTypes { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Emergency> Emergencies { get; set; }
        public virtual DbSet<EmergencyCluster> EmergencyClusters { get; set; }
        public virtual DbSet<EmergencyLocation> EmergencyLocations { get; set; }
        public virtual DbSet<EmergencyObjective> EmergencyObjectives { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<ErrorLogApplication> ErrorLogApplications { get; set; }
        public virtual DbSet<FTSFundingDetail> FTSFundingDetails { get; set; }
        public virtual DbSet<FTSFunding> FTSFundings { get; set; }
        public virtual DbSet<GenderCategory> GenderCategories { get; set; }
        public virtual DbSet<HumanitarianPriority> HumanitarianPriorities { get; set; }
        public virtual DbSet<ImportCLDataStaging_Temp> ImportCLDataStaging_Temp { get; set; }
        public virtual DbSet<ImportCLDataStagingTable> ImportCLDataStagingTables { get; set; }
        public virtual DbSet<ImportSRPFramework> ImportSRPFrameworks { get; set; }
        public virtual DbSet<ImportSRPStaging> ImportSRPStagings { get; set; }
        public virtual DbSet<ImportSRPTemp> ImportSRPTemps { get; set; }
        public virtual DbSet<IndicatorApproved> IndicatorApproveds { get; set; }
        public virtual DbSet<IndicatorCalculationType> IndicatorCalculationTypes { get; set; }
        public virtual DbSet<IndicatorClusterTarget> IndicatorClusterTargets { get; set; }
        public virtual DbSet<IndicatorComment> IndicatorComments { get; set; }
        public virtual DbSet<IndicatorCommentsDetail> IndicatorCommentsDetails { get; set; }
        public virtual DbSet<IndicatorDetail> IndicatorDetails { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<KeyFigureCategory> KeyFigureCategories { get; set; }
        public virtual DbSet<KeyFigureCategoryDetail> KeyFigureCategoryDetails { get; set; }
        public virtual DbSet<KeyFigureDetail> KeyFigureDetails { get; set; }
        public virtual DbSet<KeyFigureIndicatorDetail> KeyFigureIndicatorDetails { get; set; }
        public virtual DbSet<KeyFigureIndicator> KeyFigureIndicators { get; set; }
        public virtual DbSet<KeyFigureReport> KeyFigureReports { get; set; }
        public virtual DbSet<KeyFigureSubCategory> KeyFigureSubCategories { get; set; }
        public virtual DbSet<KeyFigureSubCategoryDetail> KeyFigureSubCategoryDetails { get; set; }
        public virtual DbSet<LocationCategory> LocationCategories { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<MapType> MapTypes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<ObjectivePriority> ObjectivePriorities { get; set; }
        public virtual DbSet<Objective> Objectives { get; set; }
        public virtual DbSet<OPSProjectDetail> OPSProjectDetails { get; set; }
        public virtual DbSet<OPSReportDetail> OPSReportDetails { get; set; }
        public virtual DbSet<OPSReportLocation> OPSReportLocations { get; set; }
        public virtual DbSet<OPSReport> OPSReports { get; set; }
        public virtual DbSet<OrganizationRequest> OrganizationRequests { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrganizationType> OrganizationTypes { get; set; }
        public virtual DbSet<ORSDataEntryVersion> ORSDataEntryVersions { get; set; }
        public virtual DbSet<ORSDocument> ORSDocuments { get; set; }
        public virtual DbSet<PasswordReset> PasswordResets { get; set; }
        public virtual DbSet<PriorityActivity> PriorityActivities { get; set; }
        public virtual DbSet<ProjectIndicatorAnnualTarget> ProjectIndicatorAnnualTargets { get; set; }
        public virtual DbSet<ProjectIndicator> ProjectIndicators { get; set; }
        public virtual DbSet<ProjectOrganization> ProjectOrganizations { get; set; }
        public virtual DbSet<ProjectPartnerActivity> ProjectPartnerActivities { get; set; }
        public virtual DbSet<ProjectPartnerActLocation> ProjectPartnerActLocations { get; set; }
        public virtual DbSet<ProjectPartnerActLocOrganization> ProjectPartnerActLocOrganizations { get; set; }
        public virtual DbSet<ProjectPartnerPresence> ProjectPartnerPresences { get; set; }
        public virtual DbSet<ProjectPartner> ProjectPartners { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<Quarter> Quarters { get; set; }
        public virtual DbSet<RegionalIndicator> RegionalIndicators { get; set; }
        public virtual DbSet<RegionalIndicatorsHistory> RegionalIndicatorsHistories { get; set; }
        public virtual DbSet<ReportDataEntryAccum> ReportDataEntryAccums { get; set; }
        public virtual DbSet<ReportDataEntryDetail> ReportDataEntryDetails { get; set; }
        public virtual DbSet<ReportDataEntryLocation> ReportDataEntryLocations { get; set; }
        public virtual DbSet<ReportDetail> ReportDetails { get; set; }
        public virtual DbSet<ReportDetailsGender> ReportDetailsGenders { get; set; }
        public virtual DbSet<ReportFrequencyType> ReportFrequencyTypes { get; set; }
        public virtual DbSet<ReportIndicatorAccumulative> ReportIndicatorAccumulatives { get; set; }
        public virtual DbSet<ReportLocation> ReportLocations { get; set; }
        public virtual DbSet<ReportProjectPartner> ReportProjectPartners { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportsDataEntry> ReportsDataEntries { get; set; }
        public virtual DbSet<ReportType> ReportTypes { get; set; }
        public virtual DbSet<SahelIndicatorCountryTarget> SahelIndicatorCountryTargets { get; set; }
        public virtual DbSet<SiteLanguage> SiteLanguages { get; set; }
        public virtual DbSet<SRPIndicator> SRPIndicators { get; set; }
        public virtual DbSet<SRPIndicatorsHistory> SRPIndicatorsHistories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<aspnet_Users_Clusters> aspnet_Users_Clusters { get; set; }
        public virtual DbSet<BulkImport_Staging> BulkImport_Staging { get; set; }
        public virtual DbSet<ImportCLDataStaging_Temp2> ImportCLDataStaging_Temp2 { get; set; }
        public virtual DbSet<KeyFigureReportDetail> KeyFigureReportDetails { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<OPSAllData> OPSAllDatas { get; set; }
        public virtual DbSet<OPSProjectsToClean> OPSProjectsToCleans { get; set; }
        public virtual DbSet<OPSUser> OPSUsers { get; set; }
        public virtual DbSet<sometable2> sometable2 { get; set; }
        public virtual DbSet<sometable3> sometable3 { get; set; }
        public virtual DbSet<StagingTableLogFrame> StagingTableLogFrames { get; set; }
        public virtual DbSet<TempData> TempDatas { get; set; }
        public virtual DbSet<Week> Weeks { get; set; }
    }
}
