//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordReset
    {
        public int PasswordResetId { get; set; }
        public string UserName { get; set; }
        public System.Guid LinkGUID { get; set; }
        public System.DateTime LinkGeneratedDate { get; set; }
        public string LinkHash { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
