//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectOrganization
    {
        public int ProjectOrganizationId { get; set; }
        public int ProjectId { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> OriginalRequest { get; set; }
        public Nullable<int> CurrentRequest { get; set; }
        public Nullable<int> RunningRequest { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ToDelete { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Project Project { get; set; }
    }
}
