//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectIndicatorAnnualTarget
    {
        public int ProjectIndicatorAnnualTargetId { get; set; }
        public int ProjectIndicatorId { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> TargetMidYear { get; set; }
        public Nullable<int> TargetFullYear { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> TargetMale { get; set; }
        public Nullable<int> TargetFemale { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CountryTargetTotal { get; set; }
        public Nullable<int> CountryTargetMale { get; set; }
        public Nullable<int> CountryTargetFemale { get; set; }
        public Nullable<int> Admin1Id { get; set; }
        public Nullable<int> Admin1TargetTotal { get; set; }
        public Nullable<int> Admin1TargetMale { get; set; }
        public Nullable<int> Admin1TargetFemale { get; set; }
        public Nullable<int> temp { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ProjectIndicator ProjectIndicator { get; set; }
    }
}
