//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalIndicatorsHistory
    {
        public int RegionalIndicatorHisotryId { get; set; }
        public int RegionalIndicatorId { get; set; }
        public int ActivityDataId { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ChangedById { get; set; }
        public System.DateTime ChangedDate { get; set; }
    }
}
