//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDataEntryLocation
    {
        public ReportDataEntryLocation()
        {
            this.ReportDataEntryDetails = new HashSet<ReportDataEntryDetail>();
        }
    
        public int ReportDataEntryLocationId { get; set; }
        public int ReportDataEntryID { get; set; }
        public int LocationId { get; set; }
    
        public virtual ICollection<ReportDataEntryDetail> ReportDataEntryDetails { get; set; }
        public virtual ReportsDataEntry ReportsDataEntry { get; set; }
    }
}
