//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SahelIndicatorCountryTarget
    {
        public int SahelIndicatorCountryTargetId { get; set; }
        public int ClusterIndicatorId { get; set; }
        public int EmergencyLocationId { get; set; }
        public int CountryClusterTarget { get; set; }
        public Nullable<int> CountryClusterTargetMale { get; set; }
        public Nullable<int> CountryClusterTargetFemale { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OriginalCountryClusterTarget { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CountryTarget { get; set; }
        public Nullable<int> CountryTargetMale { get; set; }
        public Nullable<int> CountryTargetFemale { get; set; }
    
        public virtual ClusterIndicator ClusterIndicator { get; set; }
        public virtual EmergencyLocation EmergencyLocation { get; set; }
    }
}
