//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRFROWCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int UnitIdentityId { get; set; }
        public byte SiteLanguageId { get; set; }
        public int UnitId { get; set; }
        public string Unit1 { get; set; }
        public Nullable<decimal> UnitValue { get; set; }
        public Nullable<int> BaseUnitId { get; set; }
        public Nullable<decimal> BaseUnitValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public int IsGender { get; set; }
    }
}
